${SVABENCH_ROOT}/bench/ethmac/rtl/ethmac.v

${SVABENCH_ROOT}/bench/ethmac/rtl/eth_clockgen.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_cop.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_crc.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_fifo.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_maccontrol.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_macstatus.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_miim.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_outputcontrol.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_random.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_receivecontrol.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_registers.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_rxaddrcheck.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_rxcounters.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_register.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_rxethmac.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_rxstatem.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_spram_256x32.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_shiftreg.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_transmitcontrol.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_txcounters.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_txethmac.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_txstatem.v
${SVABENCH_ROOT}/bench/ethmac/rtl/eth_wishbone.v

+incdir+${SVABENCH_ROOT}/bench/ethmac/rtl
${SVABENCH_ROOT}/bench/ethmac/rtl/ethmac_defines.v
${SVABENCH_ROOT}/bench/ethmac/rtl/timescale.v
